[build]
  publish = "dist"
  command = "npm run build"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview]
  command = "npm run build:preview"

[context.branch-deploy]
  command = "npm run build:branch"
    